### ISSUE TITLE
use_queue for queue

### ISSUE THREAD

**Issue by hermanCrespo12** [msonowal/laravel-auditor#3]
hi Manash Sonowal,
i use this package, i don't use queue for my app.
But when i change value 'use_queue' on config/mongo-audit to 'false', i still get queue list on my jobs table..
can you help me ? 
thank you

**Comment by msonowal** [comment]
@hermanCrespo12 
First of all I am glad that my package can be helpfull to you.
So, have you tried clearing caches
`php artisan config:clear` 
OR
`php artisan config:cache`

and try restarting the server if you are using in built artisan serve command to test

**Comment by hermanCrespo12** [comment]
I have tried it, but it still doesn't work
I think there is a problem with the LogsChanges.php file at variable 
`protected $ enableLoggingInQueue = true;`
I want to change the value to 'false' through models.

is there any other way ?

**Comment by msonowal** [comment]
@hermanCrespo12 
just update the value thats it `$enableLoggingInQueue = false;` in your model
